name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  auth-service:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Tidy dependencies
        run: go mod tidy

      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: go build ./...

      - name: Run go vet
        run: go vet ./...

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: staticcheck ./...

      - name: Run tests
        run: go test -vet=off ./...
